environment:
  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.5
  PGUSER: postgres
  PGPASSWORD: Password12!
  # mysql
  MYSQL_PORT: tcp://localhost:3306
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_PWD: Password12!

init:
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
  
version: '{build}'

os: Windows Server 2012

services:
  - postgresql95
  - mysql
  - mssql2017

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\Program Files (x86)\Apache\Maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  # postgres
  - createdb dbvtest
  - createdb dbvtest_cluster
  # mysql
  - mysql -e "create database dbvtest;" --user=root
  - mysql -e "create database dbvtest_cluster;" --user=root
  
  - mvn -q clean compile --batch-mode -DskipTest
test_script:
  - mvn -q test -P MSSQLServerTest,Cluster-OpenSource --batch-mode -s appveyor-settings.xml
cache:
  - C:\Users\appveyor\.m2
#on_failure:
#  - ps: |
#      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
#      Push-AppveyorArtifact surefire-reports.zip -DeploymentName "Surefire Reports"